version: "3"
services:
  backend:
    image: docker.atixlabs.com/raa/raa-backend:0.0.1-SNAPSHOT-3cb95825
    environment:
      - spring_profiles_active=${ENVIRONMENT}
      - RAA_DB=${RAA_DB}
      - RAA_DB_USER=${RAA_DB_USER}
      - RAA_DB_PASSWORD=${RAA_DB_PASSWORD}
      - CRIMSON_USER=${CRIMSON_USER}
      - CRIMSON_PASSWORD=${CRIMSON_PASSWORD}
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_URL}`)"
      - "traefik.http.routers.backend.entrypoints=web-secure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"
  frontend:
    image: docker.atixlabs.com/raa/raa-frontend:0.1.0-88c7caed
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_URL}`)"
      - "traefik.http.routers.frontend.entrypoints=web-secure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=le"
  proxy:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesResolvers.le.acme.email=info@atixlabs.com"
      - "--certificatesResolvers.le.acme.storage=/certs/acme.json"
      - "--certificatesResolvers.le.acme.httpChallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      # - ./trafeik-${ENVIRONMENT}.toml:/etc/traefik/traefik.toml
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/app/certs/:/certs"
    depends_on:
      - backend
      - frontend
  db:
    image: postgres:9.7
    environment:
      - POSTGRES_USER=${RAA_DB_USER}
      - POSTGRES_PASSWORD=${RAA_DB_PASSWORD}
      - POSTGRES_DB=${RAA_DB}
    volumes:
      - "/db-data:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:5432:5432"
  monitoring:
    image: google/cadvisor:latest
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    ports:
      - "127.0.0.1:9000:8080"